// <auto-generated />
using System;
using EF_Customer_Orders.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Customer_Orders.Migrations
{
    [DbContext(typeof(CustomerOrdersDbContext))]
    [Migration("20260212070046_InitialCreateGuid")]
    partial class InitialCreateGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("EF_Customer_Orders.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("AGENT_CODE");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("AGENT_NAME");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT")
                        .HasColumnName("COMMISSION");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("PHONE_NO");

                    b.Property<string>("WorkingArea")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT")
                        .HasColumnName("WORKING_AREA");

                    b.HasKey("Id");

                    b.HasIndex("AgentCode")
                        .IsUnique();

                    b.ToTable("AGENTS");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustCity")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUST_CITY");

                    b.Property<string>("CustCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUST_CODE");

                    b.Property<string>("CustCountry")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUST_COUNTRY");

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUST_NAME");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GRADE");

                    b.Property<decimal?>("OpeningAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("OPENING_AMT");

                    b.Property<decimal?>("OutstandingAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("OUTSTANDING_AMT");

                    b.Property<decimal?>("PaymentAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("PAYMENT_AMT");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT")
                        .HasColumnName("PHONE_NO");

                    b.Property<decimal?>("ReceiveAmt")
                        .HasColumnType("TEXT")
                        .HasColumnName("RECEIVE_AMT");

                    b.Property<string>("WorkingArea")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT")
                        .HasColumnName("WORKING_AREA");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustCode")
                        .IsUnique();

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AdvanceAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("ADVANCE_AMOUNT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrdAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("ORD_AMOUNT");

                    b.Property<DateTime?>("OrdDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ORD_DATE");

                    b.Property<string>("OrdDescription")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("ORD_DESCRIPTION");

                    b.Property<int>("OrdNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ORD_NUM");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrdNum")
                        .IsUnique();

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Customer", b =>
                {
                    b.HasOne("EF_Customer_Orders.Models.Agent", "Agent")
                        .WithMany("Customers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Order", b =>
                {
                    b.HasOne("EF_Customer_Orders.Models.Agent", "Agent")
                        .WithMany("Orders")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EF_Customer_Orders.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Agent", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EF_Customer_Orders.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
